<?php
defined('BASEPATH') OR exit('No direct script access allowed');
require_once APPPATH . 'core/MY_Superadmin_Controller.php';

/**
 * Superadmin_analytics — Phase 1C+ spoke controller for the Dashboard Hub.
 *
 * Locked design baseline: docs/design/B2_3_4_A_Analytics_Design_Locked.md
 *
 * SPOKES (one route per spoke; controller methods correspond):
 *   /superadmin/dashboard/statistics      (Phase 1C — THIS PHASE)
 *   /superadmin/dashboard/schools-search  (Phase 1D)
 *   /superadmin/dashboard/revenue         (Phase 1E)
 *   /superadmin/dashboard/cross-school    (Phase 1F)
 *   /superadmin/dashboard/tenant/{id}     (Phase 1G)
 *
 * Drill-down URL convention:
 *   /superadmin/dashboard/schools-search?state={...}&plan={...}&city={...}
 *   Generated by Phase 1C charts; consumed by Phase 1D when it ships.
 *
 * URL routing nuance:
 *   The legacy /superadmin/dashboard route is owned by Superadmin::dashboard().
 *   This controller takes /superadmin/dashboard/<spoke> via the existing
 *   CodeIgniter URL pattern of "controller name = first segment". To make
 *   /superadmin/dashboard/statistics dispatch here without adding routes.php
 *   indirection, the route file is extended at Phase 1H. For Phase 1C the
 *   spoke is reachable via the explicit class route /superadmin_analytics/statistics.
 *
 *   The Hub view's spoke navigation buttons + KPI tile links use
 *   /superadmin/dashboard/statistics; for that URL to work today, add the
 *   route alias in application/config/routes.php (Phase 1C scope keeps the
 *   alias localized — see this file's __construct() note).
 */
class Superadmin_analytics extends MY_Superadmin_Controller
{
    public function __construct()
    {
        parent::__construct();
        $this->load->library('firebase');
        $this->load->library('b2_analytics_service');
        $this->b2_analytics_service->init($this->firebase);
    }

    // ─────────────────────────────────────────────────────────────────────
    // GET /superadmin_analytics/statistics
    // (and /superadmin/dashboard/statistics via routes.php Phase 1H alias)
    // ─────────────────────────────────────────────────────────────────────
    public function statistics()
    {
        $monthsBack = (int) ($this->input->get('months', TRUE) ?? 12);
        if (!in_array($monthsBack, [3, 6, 12, 24], true)) $monthsBack = 12;

        $payload = [];
        try {
            $payload = $this->b2_analytics_service->get_statistics_payload($monthsBack);
        } catch (\Throwable $e) {
            log_message('error', 'SA statistics: ' . $e->getMessage());
        }

        $data = [
            'page_title' => 'Statistics — Super Admin',
            'payload'    => $payload,
            'monthsBack' => $monthsBack,
        ];
        $this->load->view('superadmin/include/sa_header', $data);
        $this->load->view('superadmin/analytics/statistics', $data);
        $this->load->view('superadmin/include/sa_footer');
    }

    // ─────────────────────────────────────────────────────────────────────
    // GET /superadmin_analytics/statistics_data?months={3|6|12|24}
    // AJAX refresh / range-change endpoint
    // ─────────────────────────────────────────────────────────────────────
    public function statistics_data()
    {
        $monthsBack = (int) ($this->input->get('months', TRUE) ?? 12);
        if (!in_array($monthsBack, [3, 6, 12, 24], true)) $monthsBack = 12;
        try {
            $this->json_success($this->b2_analytics_service->get_statistics_payload($monthsBack));
        } catch (\Throwable $e) {
            log_message('error', 'SA statistics_data: ' . $e->getMessage());
            $this->json_error('Statistics fetch failed.');
        }
    }

    // ─────────────────────────────────────────────────────────────────────
    // GET /superadmin_analytics/drilldown?type=lifecycle|plan|city&value=...
    // Modal-friendly drill-down content. Returns the matching tenant list.
    // ─────────────────────────────────────────────────────────────────────
    public function drilldown()
    {
        $type  = trim((string) ($this->input->get('type', TRUE)  ?? ''));
        $value = trim((string) ($this->input->get('value', TRUE) ?? ''));
        if ($type === '' || $value === '') { $this->json_error('type + value required'); return; }
        try {
            switch ($type) {
                case 'lifecycle': $rows = $this->b2_analytics_service->drilldown_schools_by_lifecycle($value); break;
                case 'plan':      $rows = $this->b2_analytics_service->drilldown_schools_by_plan($value);      break;
                case 'city':      $rows = $this->b2_analytics_service->drilldown_schools_by_city($value);      break;
                default: $this->json_error('unknown type'); return;
            }
            $this->json_success(['rows' => $rows, 'type' => $type, 'value' => $value, 'count' => count($rows)]);
        } catch (\Throwable $e) {
            log_message('error', 'SA drilldown: ' . $e->getMessage());
            $this->json_error('Drill-down failed.');
        }
    }

    // ─────────────────────────────────────────────────────────────────────
    // PHASE 1D-1G placeholders. Operator hitting these gets a "coming soon"
    // page rather than a hard 404, with backlink to the Hub.
    // ─────────────────────────────────────────────────────────────────────
    public function schools_search() { $this->_phase_pending('School Search', '1D'); }
    public function revenue()        { $this->_phase_pending('Revenue Reports', '1E'); }
    public function cross_school()   { $this->_phase_pending('Cross-School Summaries', '1F'); }
    public function tenant_detail()  { $this->_phase_pending('Per-Tenant Deep Dive', '1G'); }

    private function _phase_pending(string $spoke, string $phaseId): void
    {
        $data = [
            'page_title' => "{$spoke} — coming in Phase {$phaseId}",
            'spoke'      => $spoke,
            'phase'      => $phaseId,
        ];
        $this->load->view('superadmin/include/sa_header', $data);
        $this->load->view('superadmin/analytics/_phase_pending', $data);
        $this->load->view('superadmin/include/sa_footer');
    }
}
