<?php
/**
 * Fees Exemption v2 — Concessions & Service Enrollments admin page.
 *
 * Phase 0: both tabs are gated by config flags
 *   - $concession_ui_enabled (CONCESSION_UI_ENABLED)
 *   - $service_ui_enabled    (SERVICE_ENROLLMENT_UI_ENABLED)
 * When BOTH are off (Phase 0/1), this page renders an "Under construction"
 * placeholder — capture is structurally impossible until billing support
 * is active. The controller endpoints additionally re-check the flags
 * server-side so the gate is defense-in-depth, not view-only.
 */
?>
<div class="content-wrapper" style="padding:24px;">
<div style="max-width:1100px;margin:0 auto;">

<h1 style="font-size:1.3rem;color:var(--t1);margin:0 0 8px;">
    <i class="fa fa-percent" style="color:var(--gold);margin-right:8px;"></i>
    Concessions &amp; Service Enrollments
</h1>
<p style="color:var(--t3);font-size:13px;margin:0 0 20px;">
    Per-student dated waivers (scholarship / sibling / staff-child / management) and opt-in services
    (transport / hostel / meals). All changes are audited.
</p>

<?php if (!$concession_ui_enabled && !$service_ui_enabled): ?>

<div style="background:var(--bg2);border:1px solid var(--border);border-radius:10px;padding:32px;text-align:center;color:var(--t3);">
    <i class="fa fa-wrench" style="font-size:2rem;color:var(--gold);display:block;margin-bottom:10px;"></i>
    <h3 style="margin:0 0 6px;color:var(--t1);">Under construction</h3>
    <p style="margin:0;font-size:13px;">
        Capture is intentionally disabled until the unified fee-generation pipeline is live.
        This prevents capture-without-billing — admins can only record concessions or service
        enrollments once the engine actually applies them. Phase 0 prepares the data model,
        rules, and indexes; the capture forms light up at Phase 2 (concessions) and Phase 3
        (services) cutover.
    </p>
</div>

<?php else: ?>

<!-- Phase 2 boundary info banner (Option A scope: chart-save still on legacy). -->
<div style="background:#dbeafe;border:1px solid #93c5fd;border-radius:10px;padding:14px 18px;margin-bottom:18px;color:#1e3a8a;font-size:13px;line-height:1.55;">
    <strong><i class="fa fa-info-circle" style="margin-right:6px;"></i>Concession application — Phase 2 (Option A)</strong><br>
    Concessions created here automatically reduce demands generated by <strong>Admission</strong> and
    <strong>Promotion</strong>. They are <strong>not yet</strong> applied by Chart-Save, Manual Generation,
    Bulk Generation, or Recalc Discounts — these paths converge in Phase 2.5 (chart-save) and Phase 3
    (manual/bulk/recalc). To apply a new concession to existing demands today, <strong>re-promote</strong>
    the student (forward + reverse) — that re-runs the concession-aware generator on the destination
    class. Existing demands, payments, receipts, and parent/teacher app behavior are unchanged.
</div>

<div style="background:var(--bg2);border:1px solid var(--border);border-radius:10px;padding:16px 20px;margin-bottom:20px;">
    <label style="display:block;font-size:12px;color:var(--t3);margin-bottom:4px;">Student</label>
    <input id="fcStudent" type="text" placeholder="STU0001"
           style="padding:8px 10px;border:1px solid var(--border);border-radius:6px;background:var(--bg3);color:var(--t1);font-size:14px;min-width:240px;">
    <button onclick="fcLoad()" style="padding:8px 14px;margin-left:6px;background:var(--gold);color:#fff;border:none;border-radius:6px;cursor:pointer;">
        <i class="fa fa-search"></i> Load
    </button>
</div>

<?php if ($concession_ui_enabled): ?>
<section style="background:var(--bg2);border:1px solid var(--border);border-radius:10px;padding:20px;margin-bottom:20px;">
    <h3 style="margin:0 0 12px;color:var(--t1);font-size:1rem;"><i class="fa fa-percent"></i> Concessions</h3>
    <div id="fcConcessionsList" style="margin-bottom:14px;color:var(--t3);font-size:13px;">Load a student to see active concessions.</div>
    <details>
        <summary style="cursor:pointer;font-weight:600;color:var(--gold);font-size:13px;">+ Add concession</summary>
        <form id="fcConcessionForm" onsubmit="return fcCreateConcession(event)" style="margin-top:12px;display:grid;grid-template-columns:repeat(2,1fr);gap:10px;font-size:13px;">
            <label>Scope
                <select name="scope" required style="width:100%;padding:6px;border:1px solid var(--border);border-radius:6px;background:var(--bg3);color:var(--t1);">
                    <option value="head">Specific fee head</option>
                    <option value="category">Category (Transport / Hostel / ...)</option>
                    <option value="all">All heads</option>
                </select>
            </label>
            <label>Target (head id / category name) <input name="target" type="text" style="width:100%;padding:6px;border:1px solid var(--border);border-radius:6px;background:var(--bg3);color:var(--t1);"></label>
            <label>Type
                <select name="type" required style="width:100%;padding:6px;border:1px solid var(--border);border-radius:6px;background:var(--bg3);color:var(--t1);">
                    <option value="percent">Percent</option>
                    <option value="fixed">Fixed amount</option>
                    <option value="fullExempt">Full exempt</option>
                </select>
            </label>
            <label>Value (percent 0-100 or fixed amount) <input name="value" type="number" min="0" step="0.01" style="width:100%;padding:6px;border:1px solid var(--border);border-radius:6px;background:var(--bg3);color:var(--t1);"></label>
            <label>Effective from <input name="effective_from" type="date" required style="width:100%;padding:6px;border:1px solid var(--border);border-radius:6px;background:var(--bg3);color:var(--t1);"></label>
            <label>Effective to (optional) <input name="effective_to" type="date" style="width:100%;padding:6px;border:1px solid var(--border);border-radius:6px;background:var(--bg3);color:var(--t1);"></label>
            <label style="grid-column:1/-1;">Reason <input name="reason" type="text" required style="width:100%;padding:6px;border:1px solid var(--border);border-radius:6px;background:var(--bg3);color:var(--t1);"></label>
            <label style="grid-column:1/-1;">Approved by <input name="approved_by" type="text" style="width:100%;padding:6px;border:1px solid var(--border);border-radius:6px;background:var(--bg3);color:var(--t1);"></label>
            <button type="submit" style="grid-column:1/-1;padding:8px 14px;background:var(--gold);color:#fff;border:none;border-radius:6px;cursor:pointer;">Save concession</button>
        </form>
    </details>
</section>
<?php endif; ?>

<?php if ($service_ui_enabled): ?>
<section style="background:var(--bg2);border:1px solid var(--border);border-radius:10px;padding:20px;">
    <h3 style="margin:0 0 12px;color:var(--t1);font-size:1rem;"><i class="fa fa-bus"></i> Service enrollments</h3>
    <div id="fcEnrollmentsList" style="margin-bottom:14px;color:var(--t3);font-size:13px;">Load a student to see active enrollments.</div>
    <details>
        <summary style="cursor:pointer;font-weight:600;color:var(--gold);font-size:13px;">+ Enroll in a service</summary>
        <form id="fcEnrollForm" onsubmit="return fcEnroll(event)" style="margin-top:12px;display:grid;grid-template-columns:repeat(2,1fr);gap:10px;font-size:13px;">
            <label>Service type
                <select name="service_type" required style="width:100%;padding:6px;border:1px solid var(--border);border-radius:6px;background:var(--bg3);color:var(--t1);">
                    <option value="transport">Transport</option>
                    <option value="hostel">Hostel</option>
                    <option value="meals">Meals</option>
                </select>
            </label>
            <label>Plan ref (route id / room / plan id) <input name="plan_ref" type="text" style="width:100%;padding:6px;border:1px solid var(--border);border-radius:6px;background:var(--bg3);color:var(--t1);"></label>
            <label>Label <input name="label" type="text" style="width:100%;padding:6px;border:1px solid var(--border);border-radius:6px;background:var(--bg3);color:var(--t1);"></label>
            <label>Amount <input name="amount" type="number" min="0" step="0.01" required style="width:100%;padding:6px;border:1px solid var(--border);border-radius:6px;background:var(--bg3);color:var(--t1);"></label>
            <label>Frequency
                <select name="frequency" style="width:100%;padding:6px;border:1px solid var(--border);border-radius:6px;background:var(--bg3);color:var(--t1);">
                    <option value="monthly">Monthly</option>
                    <option value="annual">Annual</option>
                </select>
            </label>
            <label>Effective from <input name="effective_from" type="date" required style="width:100%;padding:6px;border:1px solid var(--border);border-radius:6px;background:var(--bg3);color:var(--t1);"></label>
            <label>Effective to (leave empty for open-ended) <input name="effective_to" type="date" style="width:100%;padding:6px;border:1px solid var(--border);border-radius:6px;background:var(--bg3);color:var(--t1);"></label>
            <button type="submit" style="grid-column:1/-1;padding:8px 14px;background:var(--gold);color:#fff;border:none;border-radius:6px;cursor:pointer;">Save enrollment</button>
        </form>
    </details>
</section>
<?php endif; ?>

<?php endif; /* end UI-enabled gate */ ?>

</div></div>

<?php if ($concession_ui_enabled || $service_ui_enabled): ?>
<script>
var FC_CSRF_NAME  = document.querySelector('meta[name="csrf-name"]').content;
var FC_CSRF_TOKEN = document.querySelector('meta[name="csrf-token"]').content;

function fcEsc(s) { return String(s == null ? '' : s).replace(/[&<>"']/g, function(c){return ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c];}); }

function fcPost(url, data) {
    var fd = new FormData();
    Object.keys(data).forEach(function(k){ fd.append(k, data[k] == null ? '' : data[k]); });
    fd.append(FC_CSRF_NAME, FC_CSRF_TOKEN);
    return fetch(url, { method:'POST', body: fd, headers:{ 'X-Requested-With':'XMLHttpRequest' } }).then(function(r){return r.json();});
}

function fcLoad() {
    var sid = (document.getElementById('fcStudent').value || '').trim();
    if (!sid) return;
    <?php if ($concession_ui_enabled): ?>
    fcPost('<?= base_url('fee_concessions/list_concessions') ?>', { student_id: sid }).then(function(d){
        var host = document.getElementById('fcConcessionsList');
        if (d.status !== 'success') { host.innerHTML = '<span style="color:var(--danger,#c00);">' + fcEsc(d.message || 'Load failed') + '</span>'; return; }
        if (!d.concessions || !d.concessions.length) { host.innerHTML = 'No concessions on file for ' + fcEsc(sid) + '.'; return; }
        host.innerHTML = '<table style="width:100%;border-collapse:collapse;font-size:12px;">' +
            '<thead><tr style="text-align:left;color:var(--t3);"><th style="padding:6px 8px;">Scope</th><th style="padding:6px 8px;">Target</th><th style="padding:6px 8px;">Type</th><th style="padding:6px 8px;">Value</th><th style="padding:6px 8px;">Effective</th><th style="padding:6px 8px;">Status</th><th></th></tr></thead><tbody>' +
            d.concessions.map(function(c){
                return '<tr><td style="padding:6px 8px;">' + fcEsc(c.scope) + '</td>'
                     + '<td style="padding:6px 8px;">' + fcEsc(c.targetFeeHeadId || c.targetCategory || '—') + '</td>'
                     + '<td style="padding:6px 8px;">' + fcEsc(c.type) + '</td>'
                     + '<td style="padding:6px 8px;">' + fcEsc(c.value) + '</td>'
                     + '<td style="padding:6px 8px;">' + fcEsc(c.effectiveFrom) + ' → ' + fcEsc(c.effectiveTo || '—') + '</td>'
                     + '<td style="padding:6px 8px;">' + fcEsc(c.status) + '</td>'
                     + '<td style="padding:6px 8px;">' + (c.status === 'active' ? '<button onclick="fcRevoke(\'' + fcEsc(c._id) + '\')" style="padding:3px 8px;background:#c00;color:#fff;border:none;border-radius:4px;cursor:pointer;font-size:11px;">Revoke</button>' : '') + '</td></tr>';
            }).join('') + '</tbody></table>';
    });
    <?php endif; ?>
    <?php if ($service_ui_enabled): ?>
    fcPost('<?= base_url('fee_concessions/list_enrollments') ?>', { student_id: sid }).then(function(d){
        var host = document.getElementById('fcEnrollmentsList');
        if (d.status !== 'success') { host.innerHTML = '<span style="color:var(--danger,#c00);">' + fcEsc(d.message || 'Load failed') + '</span>'; return; }
        if (!d.enrollments || !d.enrollments.length) { host.innerHTML = 'No service enrollments on file for ' + fcEsc(sid) + '.'; return; }
        host.innerHTML = '<table style="width:100%;border-collapse:collapse;font-size:12px;">' +
            '<thead><tr style="text-align:left;color:var(--t3);"><th style="padding:6px 8px;">Service</th><th style="padding:6px 8px;">Plan</th><th style="padding:6px 8px;">Amount</th><th style="padding:6px 8px;">Effective</th><th style="padding:6px 8px;">Status</th><th></th></tr></thead><tbody>' +
            d.enrollments.map(function(e){
                return '<tr><td style="padding:6px 8px;">' + fcEsc(e.serviceType) + '</td>'
                     + '<td style="padding:6px 8px;">' + fcEsc(e.planRef || e.label || '—') + '</td>'
                     + '<td style="padding:6px 8px;">' + fcEsc(e.amount) + ' / ' + fcEsc(e.frequency) + '</td>'
                     + '<td style="padding:6px 8px;">' + fcEsc(e.effectiveFrom) + ' → ' + fcEsc(e.effectiveTo || '—') + '</td>'
                     + '<td style="padding:6px 8px;">' + fcEsc(e.status) + '</td>'
                     + '<td style="padding:6px 8px;">' + (e.status === 'active' ? '<button onclick="fcDiscontinue(\'' + fcEsc(e._id) + '\')" style="padding:3px 8px;background:#c00;color:#fff;border:none;border-radius:4px;cursor:pointer;font-size:11px;">Discontinue</button>' : '') + '</td></tr>';
            }).join('') + '</tbody></table>';
    });
    <?php endif; ?>
}

<?php if ($concession_ui_enabled): ?>
function fcCreateConcession(ev) {
    ev.preventDefault();
    var fm = document.getElementById('fcConcessionForm');
    var d = {
        student_id:     document.getElementById('fcStudent').value.trim(),
        scope:          fm.scope.value,
        target:         fm.target.value,
        type:           fm.type.value,
        value:          fm.value.value,
        effective_from: fm.effective_from.value,
        effective_to:   fm.effective_to.value,
        reason:         fm.reason.value,
        approved_by:    fm.approved_by.value,
    };
    fcPost('<?= base_url('fee_concessions/create_concession') ?>', d).then(function(r){
        alert(r.message || (r.status === 'success' ? 'Saved.' : 'Failed.'));
        if (r.status === 'success') { fm.reset(); fcLoad(); }
    });
    return false;
}
function fcRevoke(id) {
    if (!confirm('Revoke this concession?')) return;
    fcPost('<?= base_url('fee_concessions/revoke_concession') ?>', { concession_id: id }).then(function(r){
        alert(r.message || (r.status === 'success' ? 'Revoked.' : 'Failed.'));
        if (r.status === 'success') fcLoad();
    });
}
<?php endif; ?>

<?php if ($service_ui_enabled): ?>
function fcEnroll(ev) {
    ev.preventDefault();
    var fm = document.getElementById('fcEnrollForm');
    var d = {
        student_id:     document.getElementById('fcStudent').value.trim(),
        service_type:   fm.service_type.value,
        plan_ref:       fm.plan_ref.value,
        label:          fm.label.value,
        amount:         fm.amount.value,
        frequency:      fm.frequency.value,
        effective_from: fm.effective_from.value,
        effective_to:   fm.effective_to.value,
    };
    fcPost('<?= base_url('fee_concessions/enroll_service') ?>', d).then(function(r){
        alert(r.message || (r.status === 'success' ? 'Saved.' : 'Failed.'));
        if (r.status === 'success') { fm.reset(); fcLoad(); }
    });
    return false;
}
function fcDiscontinue(id) {
    var to = prompt('Effective-to date (YYYY-MM-DD)?', new Date().toISOString().slice(0,10));
    if (!to) return;
    fcPost('<?= base_url('fee_concessions/discontinue_service') ?>', { enrollment_id: id, effective_to: to }).then(function(r){
        alert(r.message || (r.status === 'success' ? 'Discontinued.' : 'Failed.'));
        if (r.status === 'success') fcLoad();
    });
}
<?php endif; ?>
</script>
<?php endif; ?>
